registrasi/urls.py
from django.conf.urls import url
from .views import ViewBaseRegistrasi
from .views import ViewRegistrasi

urlpatterns = [
    url(r'^$', ViewBaseRegistrasi().home, name='home'),
    url(r'^registrasi/$', ViewRegistrasi().registrasi, name='registrasi-member'),

]

sahara/urls.py
from django.conf.urls import include, url
#from django.contrib import admin
from registrasi.admin import admin_site

urlpatterns = [
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include(admin_site.urls)),
    #url(r'^administrator/', include('administrator.urls', namespace='administrator')),
    url(r'', include('registrasi.urls', namespace='registrasi')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #url(r'', include('saharasite.urls', namespace='saharasite')),
]

registrasi/models.py
from django.db import models
from django.contrib.auth.models import User


class Paket(models.Model):
    """
    Menyimpan data Paket. tabel untuk model ini
    adalah **registrasi_paket** yang dijadikan
    FK oleh `registrasi.Registrasi`.
    """
    kode_paket = models.CharField(max_length=4, primary_key=True)
    nama_paket = models.CharField(max_length=30)
    keterangan_paket = models.TextField()
    status_paket = models.BooleanField()
    harga_paket = models.IntegerField()

    def __str__(self):
        """
        Mengembalikan string 'nama_paket'
        ke halaman html.
        """
        return self.nama_paket

    class Meta:
        verbose_name = "Paket"
        verbose_name_plural = "Master Paket"


class Pembayaran(models.Model):
    """
    Menyimpan data Jenis Pembayaran. tabel untuk model ini
    adalah **registrasi_pembayaran** yang dijadikan
    FK oleh `registrasi.Registrasi`.
    """
    kode_pembayaran = models.CharField(max_length=4, primary_key=True)
    jenis_pembayaran = models.CharField(max_length=30)

    def __str__(self):
        """
        Mengembalikan string 'jenis_pembayaran'
        ke halaman html.
        """
        return self.jenis_pembayaran

    class Meta:
        verbose_name_plural = "Master Jenis Pembayaran"



class Wilayah(models.Model):
    """
    Menyimpan data Wilayah. tabel untuk model ini
    adalah **registrasi_wilayah** yang dijadikan
    FK oleh `registrasi.Registrasi`.
    """

    kode_wilayah = models.CharField(max_length=4, primary_key=True)
    nama_wilayah = models.CharField(max_length=100, unique=True)

    def __str__(self):
        """
        Mengembalikan string 'nama_wilayah'
        ke halaman html.
        """
        return self.nama_wilayah

    class Meta:
        """
        Merepresentasikan nama models
        di aplikasi pada halaman administrator.
        """
        verbose_name_plural = "Master Wilayah"



class Registrasi(models.Model):
    """
    Class untuk menyimpan data registrasi.

    registrasi digunakan untuk menyimpan
    data calon member. calon member yang
    sudah di ceklis statusnya menjadi True
    akan menjadi member atau anggota.
    """
    nomor_registrasi = models.CharField(max_length=10, unique=True, blank=True, null=True)
    nama = models.CharField(max_length=120)
    alamat = models.TextField()
    wilayah = models.ForeignKey(Wilayah)
    email = models.EmailField()
    nomor_hp = models.CharField(max_length=16)
    tempat_lahir = models.CharField(max_length=30)
    tanggal_lahir = models.DateField()
    JENKEL = (
        ('P', 'Pria'),
        ('W', 'Wanita'),
    )
    jenis_kelamin = models.CharField(max_length=1, choices=JENKEL, default='P')
    paket = models.ForeignKey(Paket)
    pembayaran = models.ForeignKey(Pembayaran)
    status = models.BooleanField(default=False, blank=True)
    tanggal_registrasi = models.DateField(auto_now=True)


    def __str__(self):
        """
        Mengembalikan string 'nama' dari calon member
        ke halaman html.
        """
        return self.nama

    def status_member(self):
        """
        Mengembalikan nilai bool untuk status calon member.
        """
        return self.status

    status_member.boolean = True
    status_member.short_description = "SUDAH MENJADI MEMBER ?"

    def list_display_sponsor(self):
        """
        Mengembalikan nilai nomor_member sebagai
        sponsor user yang masih dalam status register.
        """
        try:
            sponsor = Sponsor.objects.get(nomor_registrasi=self)
            if not sponsor.nomor_member:
                return "--"
            else:
                return sponsor.nomor_member
        except Sponsor.DoesNotExist:
            return "--"
    list_display_sponsor.short_description = "Sponsor"

    class Meta:
        verbose_name = "Calon Member"
        verbose_name_plural = "Data Calon Member (Registrasi)"


class Member(models.Model):
    """
    Class untuk data member.

    seorang calon member yang sudah melakukan
    registrasi dan sudah mendapat persetujuan
    oleh admin akan menjadi anggota member.
    """
    nomor_member = models.CharField(max_length=12, primary_key=True)
    registrasi = models.ForeignKey(Registrasi)
    #tanggal_menjadi_member = models.DateTimeField()


    def __str__(self):
        """
        Mengembalikan string 'nama_member'
        ke halaman html.
        """
        return self.nomor_member

    def get_nomor_registrasi(self):
        return self.registrasi.nomor_registrasi
    get_nomor_registrasi.short_description = "Nomor Registrasi"

    def list_display_banyak_member(self):
        return self.sponsor_set.count()
    list_display_banyak_member.short_description = "Jumlah Pengikut Member"

    def list_display_sponsor(self):
        """
        Mengembalikan nilai nomor_member sebagai
        sponsor user.
        """
        try:
            sponsor = Sponsor.objects.get(nomor_registrasi=self.registrasi)
            if not sponsor.nomor_member:
                return "--"
            else:
                return sponsor.nomor_member
        except Sponsor.DoesNotExist:
            return "--"
    list_display_sponsor.short_description = "Di Sponsori oleh"

    class Meta:
        verbose_name_plural = "Data Member"


class Sponsor(models.Model):
    nomor_registrasi = models.ForeignKey(Registrasi, blank=True, null=True)
    nomor_member = models.ForeignKey(Member, help_text="Nomor ini sebagai nomor Sponsor Member", blank=True, null=True)
    tanggal = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.nomor_registrasi.nama

    class Meta:
        verbose_name_plural = "Sponsor"

registrasi/forms.py
from django.forms import ModelForm
from django.forms import Textarea
from django.forms import TextInput
from django.forms import Select
from django.forms import EmailInput
from django.forms import DateInput
from django.forms import RadioSelect
from django import forms

from .models import Registrasi
from .helpers.validation import validate_sponsor


class RegistrasiForm(ModelForm):
    """
    Form untuk registrasi member.
    """
    sponsor = forms.CharField(required=False,
        widget=TextInput(attrs={'class':'form-control'}),
        validators=[validate_sponsor])

    class Meta:
        model = Registrasi
        # field wajib tampil
        fields = [
            'nama', 'alamat', 'wilayah',
            'email', 'nomor_hp', 'tempat_lahir',
            'tanggal_lahir', 'jenis_kelamin','paket', 'pembayaran'
        ]
        # field yang tidak ditampilkan
        exlcude = [
            'nomor_registrasi','status',
            'tanggal_registrasi'
        ]
        # widget
        widgets = {
            'nama': TextInput(attrs={'class':'form-control'}),
            'alamat': Textarea(attrs={'class':'form-control'}),
            'wilayah': Select(attrs={'class':'form-control'}),
            'email': EmailInput(attrs={'class':'form-control'}),
            'nomor_hp': TextInput(attrs={'class':'form-control'}),
            'tempat_lahir': TextInput(attrs={'class':'form-control'}),
            'tanggal_lahir': DateInput(attrs={'class':'form-control'}),
            'jenis_kelamin': RadioSelect(attrs={'class':''}),
            'paket': Select(attrs={'class':'form-control'}),
            'pembayaran': Select(attrs={'class':'form-control'}),
        }

registrasi/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.contrib import messages
import time

from .forms import RegistrasiForm
from .helpers.generate_id import Generator
from .models import Sponsor
from .models import Registrasi
from .models import Member

class ViewBaseRegistrasi(object):
    """
    class ini seperti halnya controller. class ini
    digunakan untuk menampung method request yang bertanggung
    jawab meresponse permintaan user atau client.

    untuk digunakan di registrasi/urls.py cukup dengan::

        # http://localhost:8000/
        url(r'^$', ViewBaseRegistrasi().home, name='home'),

    """
    def home(self, request):
        context = {}
        template = 'registrasi/home.html'
        return render(request, template, context)


class ViewRegistrasi(object):

    def registrasi(self, request):
        if request.method == 'POST':
            form = RegistrasiForm(request.POST)
            #print(type(form.data.get('sponsor')))
            #print(dir(form))
            if form.is_valid():
                nomor_member_sponsor = form.data.get('sponsor')
                register = form.save(commit=False)
                register.nomor_registrasi = Generator().generate_from_date()
                register.tanggal_registrasi = timezone.now()
                register.save()
                self.__save_sponsor(nomor_member_sponsor, register)
                messages.info(request, 'Terimakasih telah registrasi.')
                return HttpResponseRedirect(reverse('registrasi:registrasi-member'))
        else:
            form = RegistrasiForm()

        context = {'form':form}
        template = 'registrasi/register.html'
        return render(request, template, context)

    def __save_sponsor(self, nomor_member_sponsor, register):
        # dapatkan objek member dari registrasi

        object_registrasi = Registrasi.objects.get(nomor_registrasi=register.nomor_registrasi)
        sponsor = Sponsor()
        if nomor_member_sponsor:
            object_member = Member.objects.get(nomor_member=nomor_member_sponsor)
            sponsor.nomor_member = object_member
            sponsor.nomor_registrasi = object_registrasi
        else:
            sponsor.nomor_registrasi = object_registrasi

        sponsor.save()

registrasi/templates/registrasi/inc/contact.html
    <section id="conatcat-info">
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <div class="media contact-info wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                        <div class="pull-left">
                            <i class="fa fa-phone"></i>
                        </div>
                        <div class="media-body">
                            <h2>Have a question or need a custom quote?</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation +0123 456 70 80</p>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/.container-->
    </section><!--/#conatcat-info-->

registrasi/templates/registrasi/inc/content.html
<section id="content">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-8 wow fadeInDown">
                   <div class="tab-wrap">
                        <div class="media">
                            <div class="parrent pull-left">
                                <ul class="nav nav-tabs nav-stacked">
                                    <li class=""><a href="#tab1" data-toggle="tab" class="analistic-01">Responsive Web Design</a></li>
                                    <li class="active"><a href="#tab2" data-toggle="tab" class="analistic-02">Premium Plugin Included</a></li>
                                    <li class=""><a href="#tab3" data-toggle="tab" class="tehnical">Predefine Layout</a></li>
                                    <li class=""><a href="#tab4" data-toggle="tab" class="tehnical">Our Philosopy</a></li>
                                    <li class=""><a href="#tab5" data-toggle="tab" class="tehnical">What We Do?</a></li>
                                </ul>
                            </div>

                            <div class="parrent media-body">
                                <div class="tab-content">
                                    <div class="tab-pane fade" id="tab1">
                                        <div class="media">
                                           <div class="pull-left">
                                                <img class="img-responsive" src="images/tab2.png">
                                            </div>
                                            <div class="media-body">
                                                 <h2>Adipisicing elit</h2>
                                                 <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use.</p>
                                            </div>
                                        </div>
                                    </div>

                                     <div class="tab-pane fade active in" id="tab2">
                                        <div class="media">
                                           <div class="pull-left">
                                                <img class="img-responsive" src="images/tab1.png">
                                            </div>
                                            <div class="media-body">
                                                 <h2>Adipisicing elit</h2>
                                                 <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use.
                                                 </p>
                                            </div>
                                        </div>
                                     </div>

                                     <div class="tab-pane fade" id="tab3">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.</p>
                                     </div>

                                     <div class="tab-pane fade" id="tab4">
                                        <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words</p>
                                     </div>

                                     <div class="tab-pane fade" id="tab5">
                                        <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures,</p>
                                     </div>
                                </div> <!--/.tab-content-->
                            </div> <!--/.media-body-->
                        </div> <!--/.media-->
                    </div><!--/.tab-wrap-->
                </div><!--/.col-sm-6-->

                <div class="col-xs-12 col-sm-4 wow fadeInDown">
                    <div class="testimonial">
                        <h2>Testimonials</h2>
                         <div class="media testimonial-inner">
                            <div class="pull-left">
                                <img class="img-responsive img-circle" src="images/testimonials1.png">
                            </div>
                            <div class="media-body">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                                <span><strong>-John Doe/</strong> Director of corlate.com</span>
                            </div>
                         </div>

                         <div class="media testimonial-inner">
                            <div class="pull-left">
                                <img class="img-responsive img-circle" src="images/testimonials1.png">
                            </div>
                            <div class="media-body">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                                <span><strong>-John Doe/</strong> Director of corlate.com</span>
                            </div>
                         </div>

                    </div>
                </div>

            </div><!--/.row-->
        </div><!--/.container-->
    </section><!--/#content-->

registrasi/templates/registrasi/inc/footer.html
<footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2015 <a target="_blank" href="#" title="Sahara Community">Sahara Community</a>. All Rights Reserved.
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->

registrasi/templates/registrasi/inc/galery_works.html
<section id="recent-works">
        <div class="container">
            <div class="center wow fadeInDown">
                <h2>Recent Works</h2>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</p>
            </div>

            <div class="row">
                <div class="col-xs-12 col-sm-4 col-md-3">
                    <div class="recent-work-wrap">
                        <img class="img-responsive" src="images/portfolio/recent/item1.png" alt="">
                        <div class="overlay">
                            <div class="recent-work-inner">
                                <h3><a href="#">Business theme</a> </h3>
                                <p>There are many variations of passages of Lorem Ipsum available, but the majority</p>
                                <a class="preview" href="images/portfolio/full/item1.png" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-4 col-md-3">
                    <div class="recent-work-wrap">
                        <img class="img-responsive" src="images/portfolio/recent/item2.png" alt="">
                        <div class="overlay">
                            <div class="recent-work-inner">
                                <h3><a href="#">Business theme</a></h3>
                                <p>There are many variations of passages of Lorem Ipsum available, but the majority</p>
                                <a class="preview" href="images/portfolio/full/item2.png" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-4 col-md-3">
                    <div class="recent-work-wrap">
                        <img class="img-responsive" src="images/portfolio/recent/item3.png" alt="">
                        <div class="overlay">
                            <div class="recent-work-inner">
                                <h3><a href="#">Business theme </a></h3>
                                <p>There are many variations of passages of Lorem Ipsum available, but the majority</p>
                                <a class="preview" href="images/portfolio/full/item3.png" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-4 col-md-3">
                    <div class="recent-work-wrap">
                        <img class="img-responsive" src="images/portfolio/recent/item4.png" alt="">
                        <div class="overlay">
                            <div class="recent-work-inner">
                                <h3><a href="#">Business theme </a></h3>
                                <p>There are many variations of passages of Lorem Ipsum available, but the majority</p>
                                <a class="preview" href="images/portfolio/full/item4.png" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-4 col-md-3">
                    <div class="recent-work-wrap">
                        <img class="img-responsive" src="images/portfolio/recent/item5.png" alt="">
                        <div class="overlay">
                            <div class="recent-work-inner">
                                <h3><a href="#">Business theme</a></h3>
                                <p>There are many variations of passages of Lorem Ipsum available, but the majority</p>
                                <a class="preview" href="images/portfolio/full/item5.png" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-4 col-md-3">
                    <div class="recent-work-wrap">
                        <img class="img-responsive" src="images/portfolio/recent/item6.png" alt="">
                        <div class="overlay">
                            <div class="recent-work-inner">
                                <h3><a href="#">Business theme </a></h3>
                                <p>There are many variations of passages of Lorem Ipsum available, but the majority</p>
                                <a class="preview" href="images/portfolio/full/item6.png" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-4 col-md-3">
                    <div class="recent-work-wrap">
                        <img class="img-responsive" src="images/portfolio/recent/item7.png" alt="">
                        <div class="overlay">
                            <div class="recent-work-inner">
                                <h3><a href="#">Business theme </a></h3>
                                <p>There are many variations of passages of Lorem Ipsum available, but the majority</p>
                                <a class="preview" href="images/portfolio/full/item7.png" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-4 col-md-3">
                    <div class="recent-work-wrap">
                        <img class="img-responsive" src="images/portfolio/recent/item8.png" alt="">
                        <div class="overlay">
                            <div class="recent-work-inner">
                                <h3><a href="#">Business theme </a></h3>
                                <p>There are many variations of passages of Lorem Ipsum available, but the majority</p>
                                <a class="preview" href="images/portfolio/full/item8.png" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.row-->
        </div><!--/.container-->
    </section><!--/#recent-works-->

registrasi/templates/registrasi/inc/menuutama.html
{% load staticfiles %}
    <header id="header">
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-xs-4">
                        <div class="top-number"><p><i class="fa fa-phone-square"></i>  +021 8977 676</p></div>
                    </div>
                    <div class="col-sm-6 col-xs-8">
                       <div class="social">
                            <ul class="social-share">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-skype"></i></a></li>
                            </ul>
                            <div class="search">
                                <form role="form">
                                    <input type="text" class="search-form" autocomplete="off" placeholder="Search">
                                    <i class="fa fa-search"></i>
                                </form>
                           </div>
                       </div>
                    </div>
                </div>
            </div><!--/.container-->
        </div><!--/.top-bar-->

        <nav class="navbar navbar-inverse" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.html"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
                </div>
				
                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'registrasi:home' %}">Home</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Product</a></li>
                        <li><a href="#">Contact Us</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Register <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'registrasi:registrasi-member' %}">Register Member</a></li>
                                <li><a href="#">Login Member</a></li>
                                <li><a href="{% url 'admin:index' %}">Login Admin</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->
		
    </header><!--/header-->

registrasi/templates/registrasi/inc/partner.html
 <section id="partner">
        <div class="container">
            <div class="center wow fadeInDown">
                <h2>Our Partners</h2>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</p>
            </div>

            <div class="partners">
                <ul>
                    <li> <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms" src="images/partners/partner1.png"></a></li>
                    <li> <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms" src="images/partners/partner2.png"></a></li>
                    <li> <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="900ms" src="images/partners/partner3.png"></a></li>
                    <li> <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="1200ms" src="images/partners/partner4.png"></a></li>
                    <li> <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="1500ms" src="images/partners/partner5.png"></a></li>
                </ul>
            </div>
        </div><!--/.container-->
    </section><!--/#partner-->